# Generated by Django 2.1.2 on 2020-01-12 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
