# Generated by Django 2.1.2 on 2020-01-13 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_roomjoinrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomjoinrequest',
            old_name='room_id',
            new_name='room',
        ),
        migrations.RenameField(
            model_name='roomjoinrequest',
            old_name='user_id',
            new_name='user',
        ),
    ]
