# Generated by Django 2.1.2 on 2020-01-18 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0010_auto_20200114_0132'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='作成時間')),
            ],
        ),
        migrations.AddField(
            model_name='roomjoinrequest',
            name='is_owner',
            field=models.BooleanField(default=False, verbose_name='オーナーである'),
        ),
        migrations.AlterField(
            model_name='room',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='詳細'),
        ),
        migrations.AlterField(
            model_name='roomjoinrequest',
            name='user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ユーザID'),
        ),
        migrations.AddField(
            model_name='roomuser',
            name='room',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='app.Room', verbose_name='部屋ID'),
        ),
        migrations.AddField(
            model_name='roomuser',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザID'),
        ),
    ]
