# Generated by Django 2.1.2 on 2020-01-20 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0013_roomjoinrequest_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True, verbose_name='コメント')),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='作成時間')),
                ('room', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='app.Room', verbose_name='部屋ID')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザID')),
            ],
        ),
        migrations.AlterField(
            model_name='roomjoinrequest',
            name='is_approved',
            field=models.BooleanField(default=False, editable=False, verbose_name='承認済み'),
        ),
        migrations.AlterField(
            model_name='roomuser',
            name='is_owner',
            field=models.BooleanField(default=False, editable=False, verbose_name='オーナーである'),
        ),
    ]
