# Generated by Django 2.1.2 on 2020-03-15 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20200120_2345'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oshihiki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.FloatField(blank=True, null=True, verbose_name='点数')),
            ],
        ),
    ]
