# Generated by Django 2.1.2 on 2020-03-16 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20200316_0251'),
    ]

    operations = [
        migrations.AddField(
            model_name='oshihiki',
            name='is_ryokei',
            field=models.BooleanField(default=True, editable=False, verbose_name='待ち'),
        ),
    ]
