# Generated by Django 2.1.2 on 2020-03-16 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_oshihiki_is_ryokei'),
    ]

    operations = [
        migrations.AddField(
            model_name='oshihiki',
            name='is_dora',
            field=models.BooleanField(default=False, editable=False, verbose_name='一発 or ドラ'),
        ),
    ]
