from .base import *

import os

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = os.environ.get('SOCIAL_AUTH_GOOGLE_OAUTH2_KEY')
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = os.environ.get(
    'SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET')

GOOGLE_ANALYTICS_TRACKING_ID = 'UA-55424845-2'

DEBUG = False
ALLOWED_HOSTS = ['*']
