# Generated by Django 2.1.2 on 2020-01-12 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_delete_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='タイトル')),
                ('content', models.TextField(blank=True, null=True, verbose_name='内容')),
                ('place', models.CharField(blank=True, max_length=50, null=True, verbose_name='場所')),
                ('start_at', models.DateTimeField(blank=True, null=True, verbose_name='開始日時')),
            ],
        ),
    ]
