# Generated by Django 2.1.2 on 2020-01-18 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200118_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomjoinrequest',
            name='is_owner',
        ),
        migrations.AddField(
            model_name='roomuser',
            name='is_owner',
            field=models.BooleanField(default=False, verbose_name='オーナーである'),
        ),
    ]
