# Generated by Django 2.1.2 on 2020-01-18 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20200118_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomjoinrequest',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='承認済み'),
        ),
    ]
